### ISSUE TITLE
compiling issue

### ISSUE THREAD

**Issue by bastianheimburger** [alekseyzimin/masurca#1]
Dear Mr Zimin,

I'd like to compile Masurca on our server. I've followed all your steps, but once I run make, I receive the attached error message (
[error.txt](https://github.com/alekseyzimin/masurca/files/1655888/error.txt)
). Please can you help me to solve my problem.

Cheers

Bastian Heimburger

**Comment by alekseyzimin** [comment]
To compile from the development tree you will need SWIG and YAGGO installed and available in the path.  You can download the tarball from the release 3.2.4 section and follow the installation instructions and you should have no problems.

**Comment by claumer** [comment]
With both yaggo and swig installed and in my path and seeming to function properly, I also see a similar error to Bastian's when trying to make MaSuRCA 3.2.5 (see attached) through the current git commit. 

[masurca_3.2.5_make_error.txt](https://github.com/alekseyzimin/masurca/files/1790523/masurca_3.2.5_make_error.txt)

The distribution tarballs seem to function alright, however, when unpacked from the cloned git directory.
