### ISSUE TITLE
nucmer error

### ISSUE THREAD

**Issue by potant** [alekseyzimin/masurca#100]
trying to  run assemble.sh the nucmer fails (in  deduplicate_contigs.sh) The error is 

nucmer: error while loading shared libraries: libumdmummer.so.0: cannot open shared object file: no such file or directory. 
The nucmer command exists under bin/ folder and libumdmummer.so.0 is in lib/
Any idea?
Thanx

**Comment by alekseyzimin** [comment]
You probably have another installation of MUMmer on your system (from bioconda?)
