### ISSUE TITLE
error running illumina and Nanopore reads together

### ISSUE THREAD

**Issue by madhubioinfo** [alekseyzimin/masurca#104]
Hi 
I am trying to run illumina MP , PE and nanopore reads and this is the error i am getting when I do
Filtering mate pairs
[Tue Mar 26 03:10:41 UTC 2019] Super reads failed, check super2.err and files in ./work2/
 
when I check the super2.err file , I found this 
mkdir work2
ufasta sizes -H /home/madhu/masurca/MaSuRCA-3.3.0/guillaumeKUnitigsAtLeast32bases_all.jump.fasta > work2/kUnitigLengths.txt; wc -l work2/kUnitigLengths.txt | awk '{print $1}' > work2/numKUnitigs.txt; tail -n 1 work2/kUnitigLengths.txt | awk '{print $1+1}' > work2/maxKUnitigNumber.txt
touch work2/createLengthStatisticsFiles.success
touch work2/createLengthStatisticsForMergedKUnitigsFiles.success
/home/madhu/masurca/MaSuRCA-3.3.0/bin/createKUnitigMaxOverlaps /home/madhu/masurca/MaSuRCA-3.3.0/guillaumeKUnitigsAtLeast32bases_all.jump.fasta -kmervalue 31 -largest-kunitig-number 6215290 work2/overlap
input file = /home/madhu/masurca/MaSuRCA-3.3.0/guillaumeKUnitigsAtLeast32bases_all.jump.fasta
largestKUnitigNumber = 6215290
touch work2/createKUnitigMaxOverlaps.success
/home/madhu/masurca/MaSuRCA-3.3.0/bin/findMatchesBetweenKUnitigsAndReads -m 31 -t 16 -o /dev/fd/1 /home/madhu/masurca/MaSuRCA-3.3.0/guillaumeKUnitigsAtLeast32bases_all.jump.fasta work2/maxKUnitigNumber.txt 161346801 sj.cor.fa | /home/madhu/masurca/MaSuRCA-3.3.0/bin/joinKUnitigs_v3 --max-nodes-allowed 2000 --mean-and-stdev-by-prefix-file meanAndStdevByPrefix.sj.txt --num-stdevs-allowed 5 --unitig-lengths-file work2/kUnitigLengths.txt --num-kunitigs-file work2/maxKUnitigNumber.txt --overlaps-file work2/overlap.overlaps --min-overlap-length 30 -o work2/readPositionsInSuperReads  -t 16 --join-aggressive 1 /dev/fd/0
Allocating 49722328 bytes for startOverlapByUnitig.
Allocating 49722328 bytes for startOverlapIndexByUnitig2.
Allocating 24861164 bytes for unitigLengths.
Allocating 139994672 bytes for unitig2OverlapIndex.
Num pairs with both reads in same unitig: 0
Num pairs uniquely joinable: 0
Num pairs after disambiguation to beginning of insert: 0
Num pairs after disambiguation to end of insert: 0
Num still joinable but not uniquely joinable: 0
Num pairs unjoinable due to missing sequence: 0
Num pairs unjoinable because there are too many nodes: 0
Num pairs with both reads in same unitig: 0
Num pairs uniquely joinable: 0
Num pairs after disambiguation to beginning of insert: 0
Num pairs after disambiguation to end of insert: 0
Num still joinable but not uniquely joinable: 0
Num pairs unjoinable due to missing sequence: 0
Num pairs unjoinable because there are too many nodes: 0
Num pairs with both reads in same unitig: 0
Num pairs uniquely joinable: 0
Num pairs after disambiguation to beginning of insert: 0
Num pairs after disambiguation to end of insert: 0
Num still joinable but not uniquely joinable: 0
Num pairs unjoinable due to missing sequence: 0
Num pairs unjoinable because there are too many nodes: 0
joiner thread Num pairs with both reads in same unitig: 0
Num pairs uniquely joinable: 0
Num pairs after disambiguation to beginning of insert: 0
Num pairs after disambiguation to end of insert: 0
Num still joinable but not uniquely joinable: 0
Num pairs unjoinable due to missing sequence: 0
Num pairs unjoinable because there are too many nodes: 0
joiner thread Num pairs with both reads in same unitig: 0
Num pairs uniquely joinable: 0
Num pairs after disambiguation to beginning of insert: 0
Num pairs after disambiguation to end of insert: 0
Num still joinable but not uniquely joinable: 0
Num pairs unjoinable due to missing sequence: 0
Num pairs unjoinable because there are too many nodes: 0
Num pairs with both reads in same unitig: 0
Num pairs uniquely joinable: 0
Num pairs after disambiguation to beginning of insert: 0
Num pairs after disambiguation to end of insert: 0
Num still joinable but not uniquely joinable: 0
Num pairs unjoinable due to missing sequence: 0
Num pairs unjoinable because there are too many nodes: 0
joiner thread 8Num pairs with both reads in same unitig: 0
Num pairs uniquely joinable: 0
Num pairs after disambiguation to beginning of insert: 0
Num pairs after disambiguation to end of insert: 0
Num still joinable but not uniquely joinable: 0
Num pairs unjoinable due to missing sequence: 0
Num pairs unjoinable because there are too many nodes: 0
joiner thread 4 returned 0Num pairs with both reads in same unitig: 0
Num pairs uniquely joinable: 0
Num pairs after disambiguation to beginning of insert: 0
Num pairs after disambiguation to end of insert: 0
Num still joinable but not uniquely joinable: 0
Num pairs unjoinable due to missing sequence: 0
Num pairs unjoinable because there are too many nodes: 0
joiner thread 3 returned 013
6 returned joiner thread Num pairs with both reads in same unitig: 0
Num pairs uniquely joinable: 0
Num pairs after disambiguation to beginning of insert: 0
Num pairs after disambiguation to end of insert: 0
Num still joinable but not uniquely joinable: 0
Num pairs unjoinable due to missing sequence: 0
Num pairs unjoinable because there are too many nodes: 0
joiner thread 11 returned 0

Num pairs with both reads in same unitig: 0
Num pairs uniquely joinable: 0
Num pairs after disambiguation to beginning of insert: 0
Num pairs after disambiguation to end of insert: 0
Num still joinable but not uniquely joinable: 0
Num pairs unjoinable due to missing sequence: 0
Num pairs unjoinable because there are too many nodes: 0
joiner thread 9Num pairs with both reads in same unitig: 0
Num pairs uniquely joinable: 0
Num pairs after disambiguation to beginning of insert: 0
Num pairs after disambiguation to end of insert: 0
Num still joinable but not uniquely joinable: 0
Num pairs unjoinable due to missing sequence: 0
Num pairs unjoinable because there are too many nodes: 0
joiner thread 5 returned 0
010 returned 0
Num pairs with both reads in same unitig: 0
Num pairs uniquely joinable: 0
Num pairs after disambiguation to beginning of insert: 0
Num pairs after disambiguation to end of insert: 0
Num still joinable but not uniquely joinable: 0
Num pairs unjoinable due to missing sequence: 0
Num pairs unjoinable because there are too many nodes: 0
joiner thread 0 returned 0Num pairs with both reads in same unitig: 0
Num pairs uniquely joinable: 0
Num pairs after disambiguation to beginning of insert: 0
Num pairs after disambiguation to end of insert: 0
Num still joinable but not uniquely joinable: 0
Num pairs unjoinable due to missing sequence: 0
Num pairs unjoinable because there are too many nodes: 0
joiner thread 12 returned Num pairs with both reads in same unitig: 0
Num pairs uniquely joinable: 0
Num pairs after disambiguation to beginning of insert: 0
Num pairs after disambiguation to end of insert: 0
Num still joinable but not uniquely joinable: 0
Num pairs unjoinable due to missing sequence: 0
Num pairs unjoinable because there are too many nodes: 0
joiner thread 7joiner thread 2 returned 0
Num pairs with both reads in same unitig: 0
Num pairs uniquely joinable: 0
Num pairs after disambiguation to beginning of insert: 0
Num pairs after disambiguation to end of insert: 0
Num still joinable but not uniquely joinable: 0
Num pairs unjoinable due to missing sequence: 0
Num pairs unjoinable because there are too many nodes: 0
joiner thread 14 returned 0 returned joiner thread 15 returned Num pairs with both reads in same unitig: 0
Num pairs uniquely joinable: 0
Num pairs after disambiguation to beginning of insert: 0
Num pairs after disambiguation to end of insert: 0
Num still joinable but not uniquely joinable: 0
Num pairs unjoinable due to missing sequence: 0
Num pairs unjoinable because there are too many nodes: 0
joiner thread 1 returned 0 returned  returned 0
0

 returned 0
00

0

Output file "work2/readPositionsInSuperReads" is of size 0, must be at least of size 1. Bye!
mv work2/readPositionsInSuperReads work2/joinKUnitigs.Failed

help me in solving this error

**Comment by alekseyzimin** [comment]
You probably have too much Illumina data in Mate Pairs.  Your sj.cor.fa file should be much smaller than pe.cor.fa
