### ISSUE TITLE
core dump, assembly finishes 

### ISSUE THREAD

**Issue by StephanHolgerD** [alekseyzimin/masurca#105]
Hey, 
I am using masurca 3.3.0 with illumina paired end and pacbio data.
The assembly finishes "normally" and the n50 seems to be okay, but there is a core file from a core dump in the working directory of masurca. 

I checked the log files an it seems like this file originates from the 8-consensus step, 
the log file of this step ends with:

ERROR: Failed with signal INT (2)
The Cleaner has arrived.  Doing 'none'.

i am not sure if this is a crucial error because masurca finished the assembly

**Comment by alekseyzimin** [comment]
Not critical, this is from one of the final CABOG executables tat generate additional information about the assembly, such as read coverage maps, etc.
