### ISSUE TITLE
runCA failed within 3-overlapcorrection

### ISSUE THREAD

**Issue by Secretloong** [alekseyzimin/masurca#107]
Hi,

I met some problems with nanopore+illumina assembling. The overlap-correction had run into failure as follow:
`
runCA failed.

----------------------------------------
Stack trace:

 at /MaSuRCA-3.3.1/bin/../CA8/Linux-amd64/bin/runCA line 1613.
        main::caFailure("19 overlap correction jobs failed; remove /"..., undef) called at /MaSuRCA-3.3.1/bin/../CA8/Linux-amd64/bin/runCA line 4514
        main::overlapCorrection() called at /MaSuRCA-3.3.1/bin/../CA8/Linux-amd64/bin/runCA line 6526

----------------------------------------
Failure message:

19 overlap correction jobs failed; remove /masurca/CA.mr.41.15.15.0.02/3-overlapcorrection/ovlcorr.sh (or run by hand) to try again
`

But the assembling could finish with remaining steps (like bogart, gatekeeper, consensus and so on). It looks like only the 3-overlapcorrection had been ignored. Is the result (./CA.mr.41.15.15.0.02/final.genome.scf.fasta) available?  

Further examine, I found the following error information. Could we fix them?
`/MaSuRCA-3.3.1/CA8/Linux-amd64/bin/correct-olaps -S /masurca/CA.mr.41.15.15.0.02/genome.ovlStore -e /masurca/CA.mr.41.15.15.0.02/3-overlapcorrection/0003.erate.WORKING /masurca/CA.mr.41.15.15.0.02/genome.gkpStore /masurca/CA.mr.41.15.15.0.02/3-overlapcorrection/genome.frgcorr 00200001 00300000
Quality Threshold = 1.50%
Allocating 15488156 words for Edit_Space.
Starting Read_Frags ()
Starting Correct_Frags ()
Starting Read_Olaps ()
Starting qsort ()
Starting Redo_Olaps ()

Failed with 'Segmentation fault'

Backtrace (mangled):

/MaSuRCA-3.3.1/CA8/Linux-amd64/bin/correct-olaps[0x406dda]
/lib64/libpthread.so.0[0x3a7c80f7e0]
/lib64/libc.so.6(fwrite+0x34)[0x3a7bc677e4]
/MaSuRCA-3.3.1/CA8/Linux-amd64/bin/correct-olaps[0x408513]
/MaSuRCA-3.3.1/CA8/Linux-amd64/bin/correct-olaps[0x407bc1]
/MaSuRCA-3.3.1/CA8/Linux-amd64/bin/correct-olaps[0x404f58]
/MaSuRCA-3.3.1/CA8/Linux-amd64/bin/correct-olaps[0x403521]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x3a7bc1ed1d]
/MaSuRCA-3.3.1/CA8/Linux-amd64/bin/correct-olaps[0x403b45]

Backtrace (demangled):

[0] /MaSuRCA-3.3.1/CA8/Linux-amd64/bin/correct-olaps() [0x406dda]
[1] /lib64/libpthread.so.0() [0x3a7c80f7e0]
[2] /lib64/libc.so.6::(null) + 0x34  [0x3a7bc677e4]
[3] /MaSuRCA-3.3.1/CA8/Linux-amd64/bin/correct-olaps() [0x408513]
[4] /MaSuRCA-3.3.1/CA8/Linux-amd64/bin/correct-olaps() [0x407bc1]
[5] /MaSuRCA-3.3.1/CA8/Linux-amd64/bin/correct-olaps() [0x404f58]
[6] /MaSuRCA-3.3.1/CA8/Linux-amd64/bin/correct-olaps() [0x403521]
[7] /lib64/libc.so.6::(null) + 0xfd  [0x3a7bc1ed1d]
[8] /MaSuRCA-3.3.1/CA8/Linux-amd64/bin/correct-olaps() [0x403b45]

GDB:

Segmentation fault
`

Thank you very much!

**Comment by alekseyzimin** [comment]
There is a workaround for this problem. You should just be able to re-generate assemble.sh and re-run.  Otherwise add 
doFragmentCorrection=0 
to CA_PARAMETERS line in config file, re-generate assemble.sh and re-run
