### ISSUE TITLE
Flye assembler command line option error in mega_reads_assemble_cluster.sh

### ISSUE THREAD

**Issue by rosscrowhurst** [alekseyzimin/masurca#120]
When I ran a hybrid assembly with 3.3.3b using flye (version 2.4.2)

```
FLYE_ASSEMBLY=1
```

the assembly falls over at the flye step with the following error:

```
usage: flye (--pacbio-raw | --pacbio-corr | --nano-raw |
             --nano-corr | --subassemblies) file1 [file_2 ...]
             --genome-size SIZE --out-dir PATH
             [--threads int] [--iterations int] [--min-overlap int]
             [--meta] [--plasmids] [--no-trestle] [--polish-target]
             [--debug] [--version] [--help] [--resume]
flye: error: unrecognized arguments: --kmer-size 21
```

This error is due to the flye command produced in ```mega_reads_assemble_cluster.sh``` containing a hard coded ```--kmer-size``` command line option to flye. This option is not valid for my version of flye (Version: 2.4.2). 

As the --kmer-szie is hard coded in  MaSuRCA-3.3.3b/bin/mega_reads_assemble_cluster.sh it might be better to remove it or make it conditional by checking if the version of flye being used supports it perhaps as the most recent version of flye does not

My workaround is to run the flye step independently removing the ```--kmer-size 21``` but that is not ideal for automation

**Comment by alekseyzimin** [comment]
You should use the version of Flye supplied with MaSuRCA -- it is modified and it does have that option, which makes a big difference. Please make sure that the version of Flye in MaSuRCA distribution is the first on the PATH by running 
export PATH=/PATH_to_MaSuRCA_bin../Flye/bin:$PATH

**Comment by cflsjt** [comment]
@alekseyzimin this seems to be an issue for the masurca v 3.4.0

I get the same error and if I check the code:

```
grep "kmer-size" /software/bioinformatics/MaSuRCA-3.4.0/bin/mega_reads_assemble_cluster.sh
        $CA_PATH/flye -t $NUM_THREADS --nano-corr $COORDS.1$POSTFIX.fa -g \
$ESTIMATED_GENOME_SIZE --kmer-size 21 -m 2500 -oflye -i 0 1>flye.log 2>&1
```

**Comment by alekseyzimin** [comment]
MaSuRCA uses customized version of Flye distributed with MaSuRCA.  Please make sure no other installation of Flye is on the PATH in your system.  Option --kmer-size is only availabel in the version of Flye distributed with MaSuRCA.
