### ISSUE TITLE
Resolving haplotypes after MaSuRCA hybrid assembly

### ISSUE THREAD

**Issue by javijevi** [alekseyzimin/masurca#126]
My assembly size is close to the expected genome size. Does it indicates that consensus contigs have been created so that I'm losing the diploid polymorphisms?

Should it be then necessary to resolve the haplotypes (using, e.g., whatshap or purge_haplotigs) after a MaSuRCA hybrid (Illumina + PacBio) assembly?

Thanks in advance and congratulations for the great tool,

Javier.

**Comment by alekseyzimin** [comment]
Thank you! By default the assemblies are produced to be "haploid", that is the alternative haplotype is filtered out. Most of the necessary processing is done inside MaSuRCA, usually there is no need to run any post-processing software.
