### ISSUE TITLE
Test Illumina+Pacbio data set for MaSuRCA

### ISSUE THREAD

**Issue by bbista** [alekseyzimin/masurca#143]
Hello,
I got his result from the test data for Illumina+Pacbio

N50 742371
Sequence 12310514
Average 586215
E-size 799397
Count 21
Is it something that is expected?  N50 of over 650Mbp mentioned in the blogspot seems wrong somehow. 

Best,
bbista

**Comment by alekseyzimin** [comment]
Hi,

Thank you for noticing this, it should have been 650Kbp.

I will fix the blog.

Aleksey
