### ISSUE TITLE
installation issue (fatal errors & warnings)

### ISSUE THREAD

**Issue by sjfleck** [alekseyzimin/masurca#148]
Hi,
I'm new to using MaSuRCA and I'm having difficulties with the installation. I followed the directions on your page and ended up with many errors running "./install.sh". In general, here's an example of a "fatal error":

swig/perl5/swig_wrap.cpp:743:10: fatal error: EXTERN.h: No such file or directory
 #include "EXTERN.h"
          ^~~~~~~~~~
compilation terminated.

Here's a long list of all the instances of "fatal error":
Line 200: swig/perl5/swig_wrap.cpp:743:10: fatal error: EXTERN.h: No such file or directory
Line 391: src/error_correct_reads.cc:25:10: fatal error: jellyfish/atomic_gcc.hpp: No such file or directory
Line 397: src/merge_mate_pairs.cc:4:10: fatal error: jellyfish/stream_manager.hpp: No such file or directory
Line 402: src/create_database.cc:23:10: fatal error: jellyfish/mer_dna.hpp: No such file or directory
Line 451: src2/findMatchesBetweenKUnitigsAndReads.cc:31:10: fatal error: jellyfish/mer_dna.hpp: No such file or directory
Line 457: src2/createKUnitigMaxOverlaps.cc:65:10: fatal error: jellyfish/err.hpp: No such file or directory
Line 462: src/bloom_query.cc:2:10: fatal error: jellyfish/mapped_file.hpp: No such file or directory
Line 467: src/rename_filter_fastq.cc:21:10: fatal error: jellyfish/err.hpp: No such file or directory
Line 472: src/filter_overlap_file.cc:23:10: fatal error: jellyfish/jellyfish.hpp: No such file or directory
Line 477: src/error_corrected2frg.cc:24:10: fatal error: jellyfish/err.hpp: No such file or directory
Line 485: ./include/jflib/pool.hpp:22:10: fatal error: jellyfish/circular_buffer.hpp: No such file or directory
Line 490: src/create_k_unitigs_large_k2.cc:24:10: fatal error: jellyfish/jellyfish.hpp: No such file or directory
Line 496: ./src/create_k_unitigs_common.hpp:21:10: fatal error: jellyfish/thread_exec.hpp: No such file or directory
Line 501: src2/getSuperReadInsertCountsFromReadPlacementFileTwoPasses.cc:27:10: fatal error: jellyfish/err.hpp: No such file or directory
Line 505: src2/getSuperReadInsertCountsFromReadPlacementFile.cc:27:10: fatal error: jellyfish/err.hpp: No such file or directory
Line 511: src2/runByDirectory.cc:20:10: fatal error: jellyfish/err.hpp: No such file or directory
Line 516: src2/joinKUnitigs_v3.cc:48:10: fatal error: jellyfish/err.hpp: No such file or directory
Line 521: src2/collectReadSequencesForLocalGapClosing.cc:19:10: fatal error: jellyfish/err.hpp: No such file or directory
Line 525: src/sorted_merge.cc:29:10: fatal error: jellyfish/err.hpp: No such file or directory
Line 920: ./src_jf_aligner/superread_parser.hpp:8:10: fatal error: jellyfish/mer_dna.hpp: No such file or directory
Line 927: ./src_jf_aligner/superread_parser.hpp:8:10: fatal error: jellyfish/mer_dna.hpp: No such file or directory
Line 933: ./src_jf_aligner/superread_parser.hpp:8:10: fatal error: jellyfish/mer_dna.hpp: No such file or directory
Line 940: ./src_jf_aligner/jf_aligner.hpp:14:10: fatal error: jellyfish/mer_dna.hpp: No such file or directory
Line 948: ./include/jflib/pool.hpp:22:10: fatal error: jellyfish/circular_buffer.hpp: No such file or directory
Line 956: ./include/jflib/pool.hpp:22:10: fatal error: jellyfish/circular_buffer.hpp: No such file or directory
Line 963: ./src_jf_aligner/jf_aligner.hpp:14:10: fatal error: jellyfish/mer_dna.hpp: No such file or directory
Line 971: ./src_jf_aligner/jf_aligner.hpp:14:10: fatal error: jellyfish/mer_dna.hpp: No such file or directory
Line 975: ./src_jf_aligner/output_file.hpp:9:10: fatal error: jellyfish/err.hpp: No such file or directory
Line 984: ./src_jf_aligner/jf_aligner.hpp:14:10: fatal error: jellyfish/mer_dna.hpp: No such file or directory
Line 1031: swig/perl5/swig_wrap.cpp:743:10: fatal error: EXTERN.h: No such file or directory

Additionally, I'm getting many warnings. There are even more warnings than "fatal errors"
so I won't list them all. Here are a couple:

standardPregraph/contig.c:79:2: warning: implicit declaration of function ‘sortedge’; did you mean ‘loadEdge’? [-Wimplicit-function-declaration]
  sortedge();
  ^~~~~~~~
  loadEdge

standardPregraph/cutTip_graph2.c:231:2: warning: implicit declaration of function ‘linearConcatenate2’; did you mean ‘linearConcatenate’? [-Wimplicit-function-declaration]
  linearConcatenate2 ( last );
  ^~~~~~~~~~~~~~~~~~
  linearConcatenate

I'm hoping that you could help me understand why I'm getting all there errors. I will attach a text file with the entire install log as well if you're interested. Thank you,
Steve

[MaSuRCA_install.txt](https://github.com/alekseyzimin/masurca/files/4082073/MaSuRCA_install.txt)

**Comment by LisaBlazek** [comment]
how did you solve it?
i currently have the same issue

**Comment by jgorz** [comment]
I am also having the same issue.
Have you had any luck installing?

**Comment by dantefff** [comment]
It seems that the problem is compiling Jellyfish. I think this is solved by my pull request: #225

**Comment by sjfleck** [comment]
I'm sure I'm too late to help anyone, but I can show how I ultimately installed the program In Dec, 2020. I didn't actually need to assemble my genomes using MaSuRCA back in Jan, 2020. I was just doing it for fun (and failing). Nearly a year later, I actually needed to do ~20 MaSuRCA assemblies and I successfully installed and assembled the genomes using MaSuRCA-3.2.7 and MaSuRCA-3.4.3 (later renamed MaSuRCA-4.0.0 because of how much faster it was). 

I should note that I ran MaSuRCA on my university's cluster that uses the Slurm workload manager. Additionally, we load programs using the Lua module system. Here are the few steps I used to install MaSuRCA-3.4.3:

#download MaSuRCA-3.4.3.tar.gz from https://github.com/alekseyzimin/masurca
#transfer it to my personal modulefiles directory
cd /full/path/to/modulefiles
tar -zxvf MaSuRCA-3.4.3.tar.gz
cd MaSuRCA-3.4.3
module load gcc/10.2.0 #automatically available by our university
module use -a /full/path/to/modulefiles/Allluas #this is my personal directory with my .lua files
module load perl-5.32.0 #installed previously
./install.sh

And here is how I load MaSuRCA in a script that I submit to our cluster:

module load gcc/10.2.0
module use -a /full/path/to/modulefiles/Allluas
module load perl-5.32.0
module load MaSuRCA-3.4.3

**Comment by buhanfeng** [comment]
Thx @sjfleck for his sharing. But seems it only works on cluster? I'm not sure about it. Anyway, here is a more staightforward solution, running 'yum install perl-ExtUtils-Embed' in Centos or apt in Ubuntu and so on.

**Comment by sjfleck** [comment]
@buhanfeng that's right. My solution should only work in specific circumstances. I wanted to share incase other people needed to install on a platform where they don't have admin permissions. Thanks for sharing your solution as well!

**Comment by dantefff** [comment]
Hello @V-JJ 

If you don't want to mess with git, you can see my small change here: [https://github.com/alekseyzimin/masurca/pull/225/files](https://github.com/alekseyzimin/masurca/pull/225/files) and you can apply it manually in the code cloned from this repository.

**Comment by dantefff** [comment]
Anyway, im taking a look and it seems that developers have addressed the issue in the current code base. @V-JJ which version are you trying to compile?

**Comment by V-JJ** [comment]
Hello! 

I tried to install the latest version `MaSuRCA 4.1.0` . 
Today, I am going to try the small change code change that you've mentioned above.

Thanks for the fast reply!

**Comment by gargkritika** [comment]
Hello

Once I make the change in the configure file, I get the following error

/DATA3/tyr03/masurca/MaSuRCA-4.0.9/global-1/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make: *** [Makefile:398: aclocal.m4] Error 127

Please suggest a possible solution

Thank you
Best regards
Kritika
