### ISSUE TITLE
Assembly times seem too high - what am I doing wrong?

### ISSUE THREAD

**Issue by mahalel** [alekseyzimin/masurca#168]
Hi I wonder if you could please help me figure out if I'm doing something wrong as it doesn't seem right:

Am currently trying to run an assembly on version 3.4.0 using the following config:

```
DATA
PE= pe 500 50  /mnt/data/00.reads/PH70_L8_1.fq.gz /mnt/data/00.reads/PH70_L8_2.fq.gz
NANOPORE=/mnt/data/00.reads/PH70_GUPPY.fastq
END
PARAMETERS
EXTEND_JUMP_READS=0
GRAPH_KMER_SIZE = auto
USE_LINKING_MATES = 0
USE_GRID=1
GRID_ENGINE=SLURM
GRID_QUEUE=htc
GRID_BATCH_SIZE=300000000
LHE_COVERAGE=25
MEGA_READS_ONE_PASS=0
LIMIT_JUMP_COVERAGE = 300
CA_PARAMETERS =  cgwErrorRate=0.15
CLOSE_GAPS=1
NUM_THREADS = 48
JF_SIZE = 50000000000
SOAP_ASSEMBLY=0
FLYE_ASSEMBLY=1
END
```

I get "Estimated Genome Size 2475849458" 
Initial stage is completed and I get to the part where I can submit the 'sbatch' command to the slurm cluster.
In the mr_pass1 folder I have 203 "lr.batch" files.

When I submit the sbatch job to the cluster (48 core with 384GB RAM) - It seems to take about 10.5 hours to create a mr.batch file.

So if I understand this correctly the 1st megareads pass it would take 203 x 10.5 hrs ~ 88 days to complete.

This doesn't seem to match the times specified on the readme, just wondering if I'm doing something wrong or I'm missing some piece of information.

Any help is appreciated please.

**Comment by alekseyzimin** [comment]
It looks like you have a mammalian-sized genome with ~2.5Gbp of sequence.  For faster assembly I would recommend running on a single 48-core computer without the grid option.  The compute time depends on the hardware used.
