### ISSUE TITLE
IOPS requirements for MaSurca run

### ISSUE THREAD

**Issue by mahalel** [alekseyzimin/masurca#177]
Hi I am trying to look at best/cheapest options for underlying storage for MaSurca jobs.

Analyzing a run that is going on at the moment (in mr_pass2 stage) - I seem to conclude that high disk IOPS is not necessary as the data seems to be loaded in memory and only written to file once once the jf_aligner job is completed.

Which makes me wonder, is a similar process for other stages too? Or are there any stages where a file is kept open and multiple writes committed to it?

I can't find much detail on this in the documentation, would appreciate some clarity if possible please.

Regards, Andrei.

**Comment by alekseyzimin** [comment]
The stage in mr_pass2 is unique.  MaSuRCA is not very disk intensive overall.
