### ISSUE TITLE
Masurca_ STDDEV is zero. 

### ISSUE THREAD

**Issue by TejasriGopi** [alekseyzimin/masurca#203]
For Masurca assembly, in the SR_config file, the mean and standard deviation values are to be given based on the O/P of hte read_statistics. but, my .fq files gave the O/P as: mean - 150. SD- 0.
The next step is to assemble the fwd and rev strands of the .fq files. 
this throws an error stating that the SD should be a positive number. 
someone suggested me to make SD 15% of the mean. 
is this the right way to do it?
Please help me

**Comment by alekseyzimin** [comment]
Generally safe values of mean and stdev are 500 and 50 for all Illumina libraries.  If you know that your library has been sequenced from ultra-long fragments (up to 1000bp) then set the stdev to about 15% of the mean.

**Comment by TejasriGopi** [comment]
ok. that helps.
