### ISSUE TITLE
fragment or insert size?

### ISSUE THREAD

**Issue by genaev** [alekseyzimin/masurca#206]
what values should be specified for mean and stdev?
`PE = two_letter_prefix mean stdev /PATH/fwd_reads.fastq /PATH/rev_reads.fastq`

the page https://github.com/alekseyzimin/masurca/ mentions the insert size:

> The mean and stdev parameters are the library insert average length and standard deviation.

While the config mentions the size of the fragment:

> Illumina paired end reads supplied as <two-character prefix> <fragment mean> <fragment stdev>

Insert size and fragment size are different things. What is meant in this case?

![image](https://user-images.githubusercontent.com/769600/103314449-b4260c00-4a55-11eb-82a9-c4edab5ae84e.png)

**Comment by alekseyzimin** [comment]
For PE reads the first number is the fragment size.
