### ISSUE TITLE
cpuid doesn't work on ARM64

### ISSUE THREAD

**Issue by arm7star** [alekseyzimin/masurca#213]
Function cpuid in global-1/SOAPdenovo2/standardPregraph/hashFunction.c doesn't work on ARM64.
I checked MaSuRCA-3.4.3 and some features for ARM64 neon has been supported. I want to use MaSuRCA on ARM64 linux. Is there some commit to support cpuid function for ARM64.
Our ARM64 cpu supports crc32 instructions. Use soft crc will be ok too.
Thank you!

**Comment by fubingting** [comment]
https://github.com/aquaskyline/SOAPdenovo2/commit/123ae763d537795d19b19005da577fc8f95e8d5d

**Comment by fubingting** [comment]
https://github.com/aquaskyline/SOAPdenovo2/commit/123ae763d537795d19b19005da577fc8f95e8d5d

**Comment by fubingting** [comment]
https://github.com/aquaskyline/SOAPdenovo2/commit/123ae763d537795d19b19005da577fc8f95e8d5d
This patch has been added to the SOAPdenovo2 official website，how about update like this？

**Comment by arm7star** [comment]
done!
