### ISSUE TITLE
Potential Installation Bug

### ISSUE THREAD

**Issue by dorton21** [alekseyzimin/masurca#250]
I'm attempting to setup this up inside of a singularity container.
After untaring the .tar.gz into /opt/ I ran the `./install.sh`

After running for a while it spits out:
`make[1]: Leaving directory '/opt/MaSuRCA-4.0.5/Flye/src'`
`+ cp -a ../Flye /opt/MaSuRCA-4.0.5`
`cp: '../Flye' and '/opt/MaSuRCA-4.0.5/Flye' are the same file`
`FATAL:   While performing build: while running engine: exit status 1`

**Comment by Truongphikt** [comment]
@dorton21 I also run into this problem. May I asked you show to resolve this? Thanks.
