### ISSUE TITLE
is polca available in conda?

### ISSUE THREAD

**Issue by MostafaYA** [alekseyzimin/masurca#254]
Hi, 
is `polca.sh` (https://github.com/alekseyzimin/masurca#polca) script included in the masurca conda environment (v3.4.2)? 
Thanks

**Comment by MostafaYA** [comment]
no need - standalone script with few deps

**Comment by tamsinlh** [comment]
MostafaYA-

Where did you find the standalone script? I am unable to locate it.

Thanks.
