### ISSUE TITLE
runCA error

### ISSUE THREAD

**Issue by TSL-RamKrishna** [alekseyzimin/masurca#27]
I am running masurca v3.2.3. I got an error at celera assembly step. The log report is below:

[Wed 23 May 17:16:57 BST 2018] Processing pe library reads
[Wed 23 May 17:34:23 BST 2018] Average PE read length 200
[Wed 23 May 17:34:24 BST 2018] Using kmer size of 127 for the graph
MIN_Q_CHAR: 33
[Wed 23 May 17:34:25 BST 2018] Creating mer database for Quorum
[Wed 23 May 17:44:48 BST 2018] Error correct PE.
[Wed 23 May 18:49:29 BST 2018] Estimating genome size.
Estimated genome size: 641438513
[Wed 23 May 18:59:38 BST 2018] Creating k-unitigs with k=127
[Wed 23 May 19:39:32 BST 2018] Computing super reads from PE
Running mega-reads correction/assembly
Using mer size 15 for mapping, B=13, d=0.02
Using MaSuRCA files from work1, k-unitig mer 41
Estimated Genome Size 641438513
Estimated Ploidy 1
Using CA installation from /tsl/software/testing/brew/default/x86_64/Cellar/masurca/3.2.3/bin/../CA8/Linux-amd64/bin
Using 320 threads
Output prefix mr.41.15.13.0.02
Detected nanopore data, we have to rename the reads
/tsl/scratch/witekk/nanopore/high_quality_minion_data.fastq  generated
Reducing super-read k-mer size
Mega-reads pass 1
compute_psa 1578015 1250919193
Processed 500000 super reads, irreducible 359409, processing 902 super reads per second
Processed 1000000 super reads, irreducible 681217, processing 2403 super reads per second
Processed 1500000 super reads, irreducible 1016462, processing 2325 super reads per second
Processed 2000000 super reads, irreducible 1342366, processing 2083 super reads per second
Mega-reads pass 2
compute_psa 1393233 5012389650
Refining alignments
read sequence for 136f2596-55be-408d-8250-ab8b5e4e744e not found at /tsl/software/testing/brew/default/x86_64/Cellar/masurca/3.2.3/bin/add_pb_seq.pl line 19, <STDIN> line 1.
/tsl/software/testing/brew/default/x86_64/Cellar/masurca/3.2.3/bin/refine.sh: line 15: delta-filter: command not found
/tsl/software/testing/brew/default/x86_64/Cellar/masurca/3.2.3/bin/refine.sh: line 16: show-coords: command not found
Can't load '/tsl/software/testing/brew/default/x86_64/Cellar/masurca/3.2.3/bin/../lib/perl/mummer.so' for module mummer: /usr/lib64/libc.so.6: version `GLIBC_2.18' not found (required by /tsl/software/testing/brew/default/x86_64/lib/libstdc++.so.6) at /usr/lib64/perl5/DynaLoader.pm line 190.
 at /tsl/software/testing/brew/default/x86_64/Cellar/masurca/3.2.3/bin/../lib/perl/mummer.pm line 11.
Compilation failed in require at /tsl/software/testing/brew/default/x86_64/Cellar/masurca/3.2.3/bin/refine_alignments.pl line 8.
BEGIN failed--compilation aborted at /tsl/software/testing/brew/default/x86_64/Cellar/masurca/3.2.3/bin/refine_alignments.pl line 8.
rm: cannot remove ‘t..matches.0.maximal_mr.fa’: No such file or directory
rm: cannot remove ‘t..matches.0.maximal_mr.names’: No such file or directory
Joining
awk: cmd. line:1: fatal: cannot open file `mr.41.15.13.0.02.all.txt' for reading (No such file or directory)
/tsl/software/testing/brew/default/x86_64/Cellar/masurca/3.2.3/bin/mega_reads_assemble_nomatch.sh: line 269: mr.41.15.13.0.02.all.txt: No such file or directory
Generating assembly input files
awk: cmd. line:1: fatal: cannot open file `mr.41.15.13.0.02.1.fa' for reading (No such file or directory)
stat: cannot stat ‘mr.41.15.13.0.02.1.fa’: No such file or directory
/tsl/software/testing/brew/default/x86_64/Cellar/masurca/3.2.3/bin/mega_reads_assemble_nomatch.sh: line 288: /641438513/1+1: syntax error: operand expected (error token is "/641438513/1+1")
Coverage threshold for splitting unitigs is 20 minimum ovl 250
Running assembly
runCA -s runCA.spec consensus=pbutgcns -p genome -d CA.mr.41.15.13.0.02 stopAfter=consensusAfterUnitigger mr.41.15.13.0.02.1.frg mr.41.15.13.0.02.1.mates.frg cgwErrorRate=0.12 useGrid=0 scriptOnGrid=0 merylThreads=16 frgCorrThreads=1 frgCorrConcurrency=12 cnsConcurrency=6 ovlCorrConcurrency=10 ovlConcurrency=10 ovlThreads=8 ovlMemory=8GB
Assembly stopped or failed, see CA.mr.41.15.13.0.02.log
[Sun 27 May 10:06:44 BST 2018] Assembly stopped or failed, see CA.mr.41.15.13.0.02.log

**On checking the file CA.mr.41.15.13.0.02.log, it reported this:**

runCA failed.

----------------------------------------
Stack trace:

 at /tsl/software/testing/brew/default/x86_64/Cellar/masurca/3.2.3/bin/runCA line 1121.
        main::caFailure('invalid unitigger specified (bogart); must be \'utg\' or \'bog\'', undef) called at /tsl/software/testing/brew/default/x86_64/Cellar/masurca/3.2.3/bin/runCA line 706
        main::setParameters() called at /tsl/software/testing/brew/default/x86_64/Cellar/masurca/3.2.3/bin/runCA line 5314

----------------------------------------
Failure message:

invalid unitigger specified (bogart); must be 'utg' or 'bog'

The celera assembler version I am running is 6.1

**Comment by nm100** [comment]
I am getting exactly the same error. My assembly stopped too

**Comment by TSL-RamKrishna** [comment]
Anyone got any solution for this?

**Comment by TSL-RamKrishna** [comment]
Using celera assembler version 8 solves this problem
