### ISSUE TITLE
last release archive is empty?

### ISSUE THREAD

**Issue by Krasnopeev** [alekseyzimin/masurca#310]
Hi!

`https://github.com/alekseyzimin/masurca/releases/tag/v4.1.0` *tar.gz is empty? 
![Screenshot from 2023-01-12 14-54-47](https://user-images.githubusercontent.com/25318909/211999081-7d6bcca2-02e0-481f-988a-1f2d7cfa7019.png)

**Comment by salvatierra8** [comment]
weird i downloaded it without problems last week, anyway until devs fix this, you can download it from the long list of files in the code tab

**Comment by jguhlin** [comment]
Same, it downloads as a rather large HTML file.

**Comment by SarahBeecroft** [comment]
I also get the same issue

**Comment by DininduSenanayake** [comment]
FYI : This is fixed now :slightly_smiling_face:
