### ISSUE TITLE
MaSuRCA-3.2.7 fail to create kunitigs

### ISSUE THREAD

**Issue by bbalog87** [alekseyzimin/masurca#51]
Hello,
masurca-3.2.7 has stopped and generated the following error in super2.err file: 
``` ufasta sizes -H /ceph/sge-tmp/jnguinka/fbn.fish.gen/Assemblies/MaSuRCA/guillaumeKUnitigsAtLeast32bases_all.jump.fasta > work2/kUnitigLengths.txt; wc -l work2/kUnitigLengths.txt | awk '{print $1}' > work2/numKUnitigs.txt; tail -n 1 work2/kUnitigLengths.txt | awk '{print $1+1}' > work2/maxKUnitigNumber.txt
Error with file '/ceph/sge-tmp/jnguinka/fbn.fish.gen/Assemblies/MaSuRCA/guillaumeKUnitigsAtLeast32bases_all.jump.fasta'
Output file "work2/kUnitigLengths.txt" is of size 0, must be at least of size 1. Bye!
mv work2/numKUnitigs.txt work2/createLengthStatisticsFiles.Failed
mv work2/maxKUnitigNumber.txt work2/createLengthStatisticsFiles.Failed
mv work2/kUnitigLengths.txt work2/createLengthStatisticsFiles.Failed 
```

Here is the content of quorum.err 
```
[2018/07/27 17:43:53] Loading mer database
[2018/07/27 19:11:49] Loading contaminant sequences
[2018/07/27 19:11:49] Computing Poisson cutoff
[2018/07/27 19:25:46] distinct mers:5419768881 total mers:79782915223 estimated coverage:14.7207
[2018/07/27 19:25:46] lambda:0.0490691 collision_prob:0.00333333 poisson_threshold:0.0001
[2018/07/27 19:25:46] Using cutoff of 4
[2018/07/27 19:25:46] Correcting reads
[2018/07/28 01:21:11] Done 
```
The following 03 filles are all empty:
 ```
guillaumeKUnitigsAtLeast32bases_all.jump.fasta.tmp
guillaumeKUnitigsAtLeast32bases_all.fasta.tmp
ESTIMATED_GENOME_SIZE.txt
 ```
Every second read in pe.cor.tmp.log  and  sj.cor.tmp.log is skipped
Here is their content of pe.cor.tmp.log:
> tail -100  pe.cor.tmp.log 
Skipped pe2761295299: No high quality mer
Skipped pe2761295053: No high quality mer
Skipped pe2761295055: No high quality mer
Skipped pe2761295057: No high quality mer
Skipped pe2761295059: No high quality mer
Skipped pe2761295061: No high quality mer
Skipped pe2761295063: No high quality mer
Skipped pe2761295065: No high quality mer
Skipped pe2761295067: No high quality mer
Skipped pe2761295069: No high quality mer
Skipped pe2761295071: No high quality mer
Skipped pe2761295073: No high quality mer
Skipped pe2761295075: No high quality mer

 > tail sj.cor.tmp.log 
Skipped m2363681195: No high quality mer
Skipped m2363700910: No high quality mer
Skipped m2363700911: No high quality mer
Skipped m2363727470: No high quality mer
Skipped m2363727471: No high quality mer
Skipped m2363765722: No high quality mer
Skipped m2363765723: No high quality mer
Skipped m2363801496: No high quality mer
Skipped m2363801497: No high quality mer
Skipped m2363809641: No high quality mer
```

My OS is : Ubuntu 16.04 

I have no clue what might have gone wrong and at which step.

I would appreciate any help, 
Thanks

**Comment by alekseyzimin** [comment]
Most likely your reverse reads had problems in the Illumina instrument run.  Can you check if the reverse reads have sequence?

**Comment by bbalog87** [comment]
OK, some sequences in the fastq files were empty. I have just filtered out those empty sequences.
