### ISSUE TITLE
Error in assemble.sh

### ISSUE THREAD

**Issue by milw** [alekseyzimin/masurca#6]
masurca 3.2.5 writes 'CA8/Linux-amd64/bin' in assemble.sh for starting the CA run, but the install path is actually just 'CA/Linux-amd64/bin'
this is the error:
`[Mon Mar  5 09:45:54 CST 2018] Using linking mates
Using CABOG from is /media/data/software/MaSuRCA-3.2.5/bin/../CA8/Linux-amd64/bin
runCA not found at /media/data/software/MaSuRCA-3.2.5/bin/../CA8/Linux-amd64/bin!
cat: CA_dir.txt: No such file or directory
[Mon Mar  5 09:45:54 CST 2018] Assembly stopped or failed, see .log`

**Comment by alekseyzimin** [comment]
Sorry, not correct, both paths are valid.  CA/Linux-amd64/bin is CA version 6 and CA8/Linux-amd64/bin is version 8.  Version 6 works better for Illumina-only data and version 8 workd folr long-read assemblies (nanopore/pacbio).  Please do not use 3.2.5, it is not ready yet for public use.

**Comment by milw** [comment]
OK, I deleted 3.2.5 and am trying to install 3.2.4 from tarball. Make hits an error:`make[1]: Entering directory '/media/data/software/MaSuRCA-3.2.4/global-1/CA8'
  CXXLD    bin/meryl
  CXXLD    bin/overmerry
  CXXLD    bin/merTrim
  CXXLD    bin/buildUnitigs
  CXXLD    bin/bogart
  CXXLD    bin/bogus
  CXXLD    bin/bogusness
  CXXLD    bin/analyzePosMap
  CXXLD    bin/metagenomics_ovl_analyses
  CXXLD    bin/asmOutputStatistics
  CXXLD    bin/computeCoverageStat
  CXXLD    bin/chimChe
  CXXLD    bin/buildRefContigs
  CXXLD    bin/greedyFragmentTiling
lib/libseq.a(seqStore.o): In function `memset':
/usr/include/x86_64-linux-gnu/bits/string3.h:86: undefined reference to `__warn_memset_zero_len'
collect2: error: ld returned 1 exit status
`

**Comment by alekseyzimin** [comment]
What is your gcc version?

**Comment by milw** [comment]
4.9.3

**Comment by milw** [comment]
As of Mar 22 2018, the 3.2.4 source downloaded from the ftp site has installed correctly, I now have both CA and CA8 in the installation.

**Comment by farihakomel** [comment]
I am having similar issue with MaSuRCA 3.3.4 assembler :

lib/libseq.a(seqStore.o): In function `memset':
/usr/include/x86_64-linux-gnu/bits/string3.h:86: undefined reference to `__warn_memset_zero_len'
collect2: error: ld returned 1 exit status
Makefile:3344: recipe for target 'bin/meryl' failed
make[1]: *** [bin/meryl] Error 1
make[1]: *** Waiting for unfinished jobs....
src/AS_MER/merTrim.o: In function `memset':
/usr/include/x86_64-linux-gnu/bits/string3.h:86: undefined reference to `__warn_memset_zero_len'
/usr/include/x86_64-linux-gnu/bits/string3.h:86: undefined reference to `__warn_memset_zero_len'
lib/libseq.a(seqStore.o): In function `memset':
/usr/include/x86_64-linux-gnu/bits/string3.h:86: undefined reference to `__warn_memset_zero_len'
collect2: error: ld returned 1 exit status
Makefile:3324: recipe for target 'bin/merTrim' failed
make[1]: *** [bin/merTrim] Error 1
lib/libseq.a(seqStore.o): In function `memset':
/usr/include/x86_64-linux-gnu/bits/string3.h:86: undefined reference to `__warn_memset_zero_len'
collect2: error: ld returned 1 exit status
Makefile:3453: recipe for target 'bin/overmerry' failed
make[1]: *** [bin/overmerry] Error 1
make[1]: Leaving directory '/home/nadia/Downloads/MaSuRCA-3.3.4/global-1/CA8'
Makefile:847: recipe for target 'install-special' failed
make: *** [install-special] Error 2

any solutions?
