### ISSUE TITLE
MaSuRCA 3.2.8 running for days

### ISSUE THREAD

**Issue by AllisonStander** [alekseyzimin/masurca#64]
Hi, I am assembling a plant genome of estimated size 2.5 Gbp.

I am testing different assemblers on a subset of my data (2 paired-end lanes ~27 GB, and 1 MP library ~3 GB).

I have previously tested MaSuRCA 3.2.6 on a different cluster (using 150 GB of memory), on the same dataset, and it completed in 3 days.

The same dataset, run on a different cluster (56 threads) and running on v 3.2.8, has been running for 13 days, and from what I can tell, it is far from complete.

Any suggestion on why it is taking so much longer to complete? We are busy installing 3.2.6 on the new cluster, and I will see whether it runs faster than 3.2.8.

Kind regards,
Allison

**Comment by osowiecki** [comment]
So, how much time has it took in the end? I have to make a hybrid assebly for maize.
