### ISSUE TITLE
No gap closing possible

### ISSUE THREAD

**Issue by SvitlanaLukicheva** [alekseyzimin/masurca#92]
Hello,

I am trying to assemble an insect genome with MaSuRCA v.3.2.5 using Illumina PE 2x250 (80X) and Nanopore (35X). The assembly succeeds, I don't see any error message except "No gap closing possible". The result is very bad, even worse than the assembly with Illumina data only. What could be the explanation of "No gap closing possible" message? Maybe there is a problem with my Nanopore data?

There is the log:

```
Verifying PATHS...
jellyfish OK
runCA OK
createSuperReadsForDirectory.perl OK
creating script file for the actions...done.
execute assemble.sh to run assembly
[Mon Jan 21 16:11:33 CET 2019] Processing pe library reads
[Mon Jan 21 16:34:01 CET 2019] Average PE read length 250
[Mon Jan 21 16:34:02 CET 2019] Using kmer size of 151 for the graph
[Mon Jan 21 16:34:02 CET 2019] MIN_Q_CHAR: 33
[Mon Jan 21 16:34:02 CET 2019] Creating mer database for Quorum
[Mon Jan 21 17:08:04 CET 2019] Error correct PE.
[Mon Jan 21 21:23:51 CET 2019] Estimating genome size.
[Mon Jan 21 22:04:03 CET 2019] Estimated genome size: 1525394691
[Mon Jan 21 22:04:03 CET 2019] Creating k-unitigs with k=151
[Tue Jan 22 00:36:43 CET 2019] Computing super reads from PE
Using CABOG from is /svub0/slukiche/assemblers/masurca/MaSuRCA-3.2.5/bin/../CA8/Linux-amd64/bin
Running mega-reads correction/assembly
Using mer size 15 for mapping, B=15, d=0.02
Estimated Genome Size 1525394691
Estimated Ploidy 1
Using 16 threads
Output prefix mr.41.15.15.0.02
Using 30x of the longest ONT reads
Reducing super-read k-mer size
Mega-reads pass 1
Running locally in 1 batch
Mega-reads pass 2
Running locally in 1 batch
Refining alignments
Joining
Generating assembly input files
Coverage of the mega-reads less than 5 -- using the super reads as well
Coverage threshold for splitting unitigs is 15 minimum ovl 250
Running assembly
Recomputing A-stat
recomputing A-stat for super-reads
Mega-reads initial assembly complete.
[Tue Jan 22 21:47:18 CET 2019] No gap closing possible.
[Tue Jan 22 22:19:57 CET 2019] Assembly complete, final scaffold sequences are in CA.mr.41.15.15.0.02/final.genome.scf.fasta
[Tue Jan 22 22:19:57 CET 2019] All done
```

Thank you in advance!

**Comment by SvitlanaLukicheva** [comment]
I discovered that my ONT file was corrupted, I suppose it was the reason of "No gap closing possible" message.

**Comment by heingolajojo-design** [comment]
I want to assemble with Marsuca 4.1.4 using PE Illumina, but it is giving me a gap close failure. Is it advisable to bypass this step and continue with the assembly, which can not cause downstream analysis
(base) david@david-jojo:~$ conda activate masurca_env
(masurca_env) david@david-jojo:~$ nano masurca.cfg
(masurca_env) david@david-jojo:~$ masurca masurca.cfg
Verifying PATHS...
jellyfish OK
runCA OK
createSuperReadsForDirectory.perl OK
creating script file for the actions...done.
execute assemble.sh to run assembly
(masurca_env) david@david-jojo:~$ ./assemble.sh
[Thu Feb 19 09:26:09 AM UTC 2026] Processing pe library reads
[Thu Feb 19 09:26:09 AM UTC 2026] Average PE read length 150
[Thu Feb 19 09:26:09 AM UTC 2026] Using kmer size of 99 for the graph
[Thu Feb 19 09:26:09 AM UTC 2026] MIN_Q_CHAR: 33
[Thu Feb 19 09:26:09 AM UTC 2026] Estimated genome size: 189069824
[Thu Feb 19 09:26:09 AM UTC 2026] Computing super reads from PE
[Thu Feb 19 09:26:09 AM UTC 2026] Using linking mates
[Thu Feb 19 09:26:09 AM UTC 2026] Gap closing
[Thu Feb 19 09:26:17 AM UTC 2026] Gap close failed, you can still use pre-gap close files under CA/9-terminator/. Check gapClose.err for problems.
