### ISSUE TITLE
invalid forward file for PE library

### ISSUE THREAD

**Issue by MChiaraC** [alekseyzimin/masurca#99]
Hi, 
I am trying to assemble a bacterial genome from miseq paired end reads in masurca 3.3.0.
i compiled the configuration file as follows: 

DATA
#Illumina paired end reads supplied as <two-character prefix> <fragment mean> <fragment stdev> <forward_reads> <reverse_reads>
#if single-end, do not specify <reverse_reads>
#MUST HAVE Illumina paired end reads to use MaSuRCA
PE=pe 267 57 ~/projects/miseq/pant_bact/DLK2/frag_1.fastq ~/projects/miseq/pant_bact/DLK2/frag_2.fastq
#Illumina mate pair reads supplied as <two-character prefix> <fragment mean> <fragment stdev> <forward_reads> <reverse_reads>
#JUMP= sh 3600 200 
#pacbio OR nanopore reads must be in a single fasta or fastq file with absolute path, can be gzipped
#if you have both types of reads supply them both as NANOPORE type
#PACBIO=/FULL_PATH/pacbio.fa
#NANOPORE=/FULL_PATH/nanopore.fa
#Other reads (Sanger, 454, etc) one frg file, concatenate your frg files into one if you have many
#OTHER=/FULL_PATH/file.frg
END

and I get

perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
LANGUAGE = "en_US:en",
LC_ALL = (unset),
LC_CTYPE = "UTF-8",
LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
Error line 17 of configuration file 'sr_config_DLK2.txt':
invalid forward file for PE library 'pe': '~/projects/miseq/pant_bact/DLK2/frag_1.fastq' Bad file descriptor

I checked the path and the file and they seem ok... I am stuck here..
Any help?
Thanks anyway
Chiara

**Comment by HafidaB** [comment]
I am getting the same error , Have you found a solution ?

**Comment by asantat** [comment]
I have the same. I suggest you to change tilda "~" onto absolute path.
I use symlinks may be it caused the problem.
